graph TD
  pageIn[进入页面] --> begin[API: preview_repay]
  begin -->|repayAmountType为total或者总金额小于最小还金额| editable{是否不可编辑}
  editable --> |yes|repay[还款]
  editable --> |no|isFirstIn[是否首次进入]
  isFirstIn --> |yes| yellow[展示提醒建议还款]
  isFirstIn --> |no| input[输入金额]
  yellow --> input
  yellow --> repay
  input --> |监听input事件| input
  input --> big{金额是否大于最大还款}
  input --> small{金额是否小于最小还款}
  big --> |yes| showBigError[展示最大金额限制error]
  big --> |no| getInput[获取输入金额]
  small --> |yes| showSmallError[展示最小金额限制error]
  small --> |no| getInput
  showSmallError -->  disable[禁止还款]
  showBigError --> disable
  getInput --> judge[对不同国家金额做限制小数or整数]
  judge --> |合法|repay